dist: trusty
sudo: required
language: c

addons:
  apt:
    packages:
      - libcmocka-dev
      - rpm
      - valgrind

compiler:
  - clang
  - gcc

env:
  - TARGET=valgrind
  - TARGET=distcheck
  - TARGET=dist-srpm
  - TARGET=github-lambda
  - TARGET=make-embedded

matrix:
  exclude:
    - compiler: clang
      env: TARGET=dist-srpm
    - compiler: clang
      env: TARGET=github-lambda
    - compiler: clang
      env: TARGET=make-embedded

install: gem install ronn

before_script:
  - git fetch --unshallow
  - ./autogen.sh

script:
  - ./travis/build.sh
  - ./travis/deploy.sh
