dist: trusty
sudo: required
language: c

addons:
  apt:
    packages:
      - gcc-mingw-w64-i686
      - gcc-mingw-w64-x86-64
      - libcmocka-dev
      - rpm
      - valgrind

compiler:
  - clang
  - gcc

env:
  - TARGET=valgrind
  - TARGET=distcheck
  - TARGET=dist-srpm
  - TARGET=w32
  - TARGET=w64

matrix:
  exclude:
    - compiler: clang
      env: TARGET=w32
    - compiler: clang
      env: TARGET=w64
    - compiler: clang
      env: TARGET=dist-srpm

install: gem install ronn

before_script: ./autogen.sh

script: ./build-aux/travis-build.sh

deploy:
  provider: script
  script: ./build-aux/travis-deploy.sh
  skip_cleanup: true
  on:
    repo: blogc/blogc
    branch: master
    condition:
      - $CC = gcc
      - $TARGET != valgrind
