dist: trusty
sudo: required
language: c

addons:
  apt:
    packages:
      - libcmocka-dev
      - rpm
      - valgrind

compiler:
  - clang
  - gcc

env:
  - TARGET=valgrind
  - TARGET=distcheck
  - TARGET=dist-srpm
  - TARGET=blogc-github-lambda
  - TARGET=blogc-make-embedded

matrix:
  exclude:
    - compiler: clang
      env: TARGET=dist-srpm
    - compiler: clang
      env: TARGET=blogc-github-lambda
    - compiler: clang
      env: TARGET=blogc-make-embedded

install: gem install ronn

before_script:
  - git fetch --unshallow
  - ./autogen.sh

script:
  - ./build-aux/travis-build.sh
  - ./build-aux/travis-deploy.sh
