default_configure_args:
  - "CFLAGS=-Wall -g -O0"
  - --disable-silent-rules
  - --disable-valgrind
  - --enable-ronn
  - --enable-tests
  - --enable-git-receiver
  - --enable-make
  - --enable-runserver

targets:
  dist-srpm:
    configure_args:
      - --disable-tests
    archive_filter: "*.src.rpm"
  clang-analyzer:
    configure_args:
      - --enable-silent-rules
      - --disable-tests
    task_script: build-aux/clang-analyzer.sh
    archive_extract_filter: "*.tar.xz"
  valgrind:
    configure_args:
      - --enable-valgrind
  check-make-embedded:
    configure_args:
      - --disable-git-receiver
      - --disable-runserver
      - --enable-make-embedded
    task_script: build-aux/check-make-embedded.sh
  static:
    configure_args:
      - "CFLAGS=-Wall -g -O2"
      - --disable-tests
      - --disable-git-receiver
      - --disable-runserver
      - --enable-make-embedded
    task_script: build-aux/build-static.sh
  static-all:
    configure_args:
      - "CFLAGS=-Wall -g -O2"
      - --disable-tests
      - --prefix=/
    task_script: build-aux/build-static-all.sh
  win32:
    configure_args:
      - CC=
      - "CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4"
      - --host=i686-w64-mingw32
      - --target=i686-w64-mingw32
      - --disable-tests
      - --disable-git-receiver
      - --disable-make
      - --disable-runserver
    task_script: build-aux/build-windows.sh
  win64:
    configure_args:
      - CC=
      - "CFLAGS=-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4"
      - --host=x86_64-w64-mingw32
      - --target=x86_64-w64-mingw32
      - --disable-tests
      - --disable-git-receiver
      - --disable-make
      - --disable-runserver
    task_script: build-aux/build-windows.sh
